### DISCUSSION TITLE
Papermerge 2.1 on Synology NAS Docker

### DISCUSSION THREAD

**Discussion by ricosander** [ciur/papermerge#506] [Q&A]
Hi,
I was using the papermerge from linuxserver (https://github.com/linuxserver/docker-papermerge) but want to switch to this build.

Can anyone give some hints on how to set this up on a synology NAS with docker?

Thanks in advance,
Rico

**Comment by falbalae** [comment]
I have the same question. I have got even more curious after reading the documentation: apparently docker - compose is good for testing and "playing around" but not for a production environment. Kubernetes would be more appropriate: but for Kubernetes there are no instructions yet on how to proceed. And of course I know very very little about docker and nothing about Kubernetes. 

So, what we shall use to install papermerge on a synology NAS? Is docker - compose really not good enough for home use? 

The bare - metal option is not indicated for bare users, it is more appropriate for developers I read. So... how should we proceed? 

Thanks.

**Comment by stlorenz** [comment]
I just installed with this docker compose file on a DS918+ with 16GB RAM:
This already use the elasticsearch container instead of Xapian. Oon a smaller DS, I would recommend going with the standard one from the [documentation](https://docs.papermerge.io/Setup/docker-compose.html#docker-compose). 

The performance is **OK**, uploading a bunch of PDF blocks the synology for some time- OCR will not always work automatically on this machine and you must trigger it manually. 

```
version: '3.7'
x-backend: &backend
  image: papermerge/papermerge:2.1.9
  volumes:
    - media_root:/app/media
  environment:
    - PAPERMERGE__MAIN__SECRET_KEY=${SECRET_KEY}
    - PAPERMERGE__DATABASE__TYPE=postgres
    - PAPERMERGE__DATABASE__USER=${DB_USER}
    - PAPERMERGE__DATABASE__NAME=${DB_NAME}
    - PAPERMERGE__DATABASE__PASSWORD=${DB_PASSWORD}
    - PAPERMERGE__DATABASE__HOST=${DB_HOST}
    - PAPERMERGE__REDIS__HOST=redis
    - PAPERMERGE__REDIS__PORT=6379
    - DJANGO_SUPERUSER_USERNAME=${SUPERUSER_USERNAME}
    - DJANGO_SUPERUSER_EMAIL=${SUPERUSER_EMAIL}
    - DJANGO_SUPERUSER_PASSWORD=${SUPERUSER_PASSWORD}
    - DJANGO_SETTINGS_MODULE=config.settings
    - PAPERMERGE__SEARCH__ENGINE=elastic7
    - PAPERMERGE__SEARCH__URL=http://es:9200
services:
  worker:
    <<: *backend
    command: worker
  backend:
    <<: *backend
    ports:
      - '16000:8000'
  db:
    image: postgres:14.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
  redis:
    image: 'redis:6'
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
      - 9300:9300
volumes:
  postgres_data:
  media_root:
  redis_data:
````

The way to set this up depends on your DSM version. 
With Synology DSM 7.2 you can use the new "Container Manager" to upload the `docker-compose.yml`. Please find the doc [here](https://kb.synology.com/en-uk/DSM/help/ContainerManager/docker_project?version=7)
You must also adapt the file to integrate the `.env` file directly, just replace  `${SECRET_KEY}` with the actual value. 

With Synology DSM 7.1 you should use SSH to login to the Synology and create the `docker-compose.yml` manually, then run `docker-compose up -d`. This is really something for more advanced users, understanding Docker and Linux quite well. 

Kubernetes is a container orchestrator solution, it does not run on a Synology AFAIK, so please ignore that unless you know how to deploy any application on a kubernetes cluster.
