### ISSUE TITLE
Ansible Task

### ISSUE THREAD

**Issue by achembarpu** [ciur/papermerge#19]
Hey,

Thanks for this amazing software! I've taken a jab at creating an ansible task to install this, to integrate it into my personal fork of [this project](https://github.com/DaveStephens/ansible-nas). Let me know if this is something you're interested in adding to the project.

Cheers!

```yaml
---
- name: Create Papermerge Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ papermerge_data_directory }}/postgres"
    - "{{ papermerge_data_directory }}/broker"

- name: Create Postgres for Papermerge
  docker_container:
    name: papermerge-postgres
    image: postgres:11.7
    pull: yes
    state: started
    restart: yes
    volumes:
      - "{{ papermerge_data_directory }}/postgres:/var/lib/postgresql/data:rw"
    env:
      POSTGRES_USER: "papermerge"
      POSTGRES_PASSWORD: "supersecure"
    restart_policy: unless-stopped
    memory: 1g

- name: Create Papermerge service container
  docker_container:
    name: papermerge-service
    image: eugenci/papermerge
    pull: yes
    state: started
    restart: yes
    command: python3 /opt/papermerge/manage.py runserver 0.0.0.0:8000
    links:
        - papermerge-postgres:db
    ports:
      - "{{ papermerge_port }}:8000"
    env:
      POSTGRES_DB: "papermerge"
      POSTGRES_USER: "papermerge"
      POSTGRES_PASSWORD: "supersecure"
      DJANGO_SETTINGS_MODULE: "config.settings.stage"
    volumes:
      - "{{ papermerge_media_directory }}:/opt/media:ro"
      - "{{ papermerge_data_directory }}/broker:/opt/broker/queue:rw"
    restart_policy: unless-stopped
    memory: 1g

- name: Create Papermerge worker container
  docker_container:
    name: papermerge-worker
    image: eugenci/papermerge-worker
    pull: yes
    state: started
    restart: yes
    command: bash -c "cd /opt/papermerge-worker && celery worker -A pmworker.celery -Q papermerge -l info"
    env:
      CELERY_CONFIG_MODULE: "config"
      C_FORCE_ROOT: "true"
    volumes:
      - "{{ papermerge_media_directory }}:/opt/media:ro"
      - "{{ papermerge_data_directory }}/broker:/opt/broker/queue:rw"
    restart_policy: unless-stopped
    memory: 1g
```
