### ISSUE TITLE
Support for platform "linux/arm64/v8" requested to allow running Papermerge 3.0 on a Raspberry Pi

### ISSUE THREAD

**Issue by veitenti** [ciur/papermerge#580]
The docker images provided in the documentation do not support the platform linux/arm64/v8 at the moment. This causes the docker compose file to not work.

**Reproduction steps:**

- Create a `docker-compose.yml` with the content shown in the [installation guide](https://docs.papermerge.io/3.0/setup/docker-compose/):

```
  version: "3.9"

  x-backend: &common
    image: papermerge/papermerge:3.0.1
    environment:
        PAPERMERGE__SECURITY__SECRET_KEY: 12345
        PAPERMERGE__AUTH__USERNAME: john
        PAPERMERGE__AUTH__PASSWORD: hohoho
        PAPERMERGE__REDIS__URL: redis://redis:6379/0
    volumes:
        - data:/db
        - index_db:/core_app/index_db
        - media:/core_app/media
  services:
    web:
      <<: *common
      ports:
       - "12000:80"
      depends_on:
        - redis
    worker:
      <<: *common
      command: worker
    redis:
      image: redis:6
  volumes:
    data:
    index_db:
    media:

```

- Call `docker compose up -d web worker redis`
- Output is `The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested` ❌

**Goal:**
Add support for platform "linux/arm64/v8" please 😃
