### ISSUE TITLE
After restart Papermerge did not save documents

### ISSUE THREAD

**Issue by deimjons** [ciur/papermerge#613]
**Description**
After docker restart of papermerge it does not save documents. Please help to solve this ossue

**Info:**
 - Papermerge Version [e.g. 3.1]
 
 My docker-compose.yml
 
```
 version: '3.9'
services:
  papermerge:
    # image: papermerge/papermerge:3.1
    build: .
    container_name: papermerge
    depends_on:
      - papermerge_redis
      - papermerge_db
    environment:
        PAPERMERGE__SECURITY__SECRET_KEY: 12345
        PAPERMERGE__AUTH__USERNAME: admin
        PAPERMERGE__AUTH__PASSWORD: MnSA8Eji4nK6WNeYUJZajPtuG
        PAPERMERGE__DATABASE__URL: postgresql://papermerge:BRgJbm4JcyqxXQCiGxWd84Wik@papermerge_db:5432/papermerge
        PAPERMERGE__REDIS__URL: redis://papermerge_redis:6379/0
    labels:
      traefik.enable: true
      traefik.docker.network: traefik

      traefik.http.routers.papermerge-http.rule: Host(`papermerge.example.com`)
      traefik.http.routers.papermerge-http.entrypoints: web
      traefik.http.routers.papermerge-http.middlewares: https-redirect

      traefik.http.routers.papermerge-https.rule: Host(`papermerge.example.com`)
      traefik.http.routers.papermerge-https.entrypoints: websecure
      traefik.http.routers.papermerge-https.tls: true
      traefik.http.routers.papermerge-https.tls.certresolver: prod
    volumes:
      - index_db:/core_app/index_db
      - media:/core_app/media
    networks:
      - papermerge
      - traefik
    ports:
      - 8888:80

  papermerge_worker:
    image: papermerge/papermerge:3.0.3
    container_name: papermerge_worker
    environment:
        PAPERMERGE__SECURITY__SECRET_KEY: 12345
        PAPERMERGE__AUTH__USERNAME: admin
        PAPERMERGE__AUTH__PASSWORD: MnSA8Eji4nK6WNeYUJZajPtuG
        PAPERMERGE__DATABASE__URL: postgresql://papermerge:BRgJbm4JcyqxXQCiGxWd84Wik@papermerge_db:5432/papermerge
        PAPERMERGE__REDIS__URL: redis://papermerge_redis:6379/0
    command: worker
    volumes:
      - index_db:/core_app/index_db
      - media:/core_app/media
    networks:
      - papermerge

  papermerge_redis:
    image: redis:6
    container_name: papermerge_redis
    networks:
      - papermerge

  papermerge_db:
    image: bitnami/postgresql:16.1.0
    container_name: papermerge_db
    environment:
      POSTGRESQL_USER: papermerge
      POSTGRESQL_PASSWORD: BRgJbm4JcyqxXQCiGxWd84Wik
      POSTGRESQL_POSTGRES_PASSWORD: BRgJbm4JcyqxXQCiGxWd84Wik
      POSTGRESQL_DATABASE: papermerge
    volumes:
      - postgres_db:/var/lib/postgresql/data/
    networks:
      - papermerge

volumes:
  media:
  index_db:
  postgres_db:

networks:
  traefik:
    external: true
  papermerge:
    name: papermerge
```
