### ISSUE TITLE
Docker installation for PaperMerge 3.2

### ISSUE THREAD

**Issue by alz3abi** [ciur/papermerge#620]
### Discussed in https://github.com/ciur/papermerge/discussions/619

<div type='discussions-op-text'>

<sup>Originally posted by **alz3abi** June 21, 2024</sup>
Hello Folks,

I'm trying to install papermerge on docker, tried there Setup guide with no luck looks like django not reading the configurations properly.

i used this compose filw with no luck ( error with port, container listen to 7000 and setup added as 80)

```
version: "3.9"

x-backend: &common
  image: papermerge/papermerge:3.2
  environment:
      PAPERMERGE__SECURITY__SECRET_KEY: 12345
      PAPERMERGE__AUTH__USERNAME: admin
      PAPERMERGE__AUTH__PASSWORD: admin
      PAPERMERGE__REDIS__URL: redis://redis:6379/0
  volumes:
      - data:/db
      - index_db:/core_app/index_db
      - media:/core_app/media
services:
  web:
    <<: *common
    ports:
     - "12000:80"
    depends_on:
      - redis
  worker:
    <<: *common
    command: worker
  redis:
    image: redis:6
volumes:
    data:
    index_db:
    media:
```
then updated 12000:7000 a got it running with error of 500 in webUI

any help on this ?</div>
